version: "3.8"
services:
  api:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/collab_notes
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: collab_notes
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "6543:5432"

volumes:
  pgdata:
